# Generated by Django 4.2.16 on 2025-04-21 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0010_alter_badges_image_alter_person_profile_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participation',
            old_name='high',
            new_name='senior',
        ),
    ]
