# Generated by Django 4.2.16 on 2025-04-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0011_rename_high_participation_senior'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='badges',
            field=models.ManyToManyField(blank=True, help_text='Badges awarded for this specific participation', related_name='participations', to='experiences.badges'),
        ),
    ]
