# Generated by Django 4.2.16 on 2025-04-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0012_participation_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='show_activities_publicly',
            field=models.BooleanField(default=False, help_text='Whether to show activities on public profile'),
        ),
        migrations.AddField(
            model_name='person',
            name='show_guardians_publicly',
            field=models.BooleanField(default=False, help_text='Whether to show guardians on public profile'),
        ),
    ]
