# Generated by Django 4.2.16 on 2025-04-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0013_person_show_activities_publicly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='badges',
            field=models.ManyToManyField(blank=True, help_text='Badges displayed for this group', related_name='groups', to='experiences.badges'),
        ),
    ]
