# Generated by Django 4.2.16 on 2025-05-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0014_group_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether this participation is visible on public profiles'),
        ),
    ]
