# Generated by Django 4.2.21 on 2025-05-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0015_participation_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='cached_str',
            field=models.CharField(blank=True, editable=False, help_text='Cached string representation of this person', max_length=255),
        ),
    ]
