# Generated by Django 4.2.21 on 2025-05-19 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0017_recreate_participation_badges_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badges',
            name='core_competencies',
            field=models.ManyToManyField(blank=True, to='experiences.corecompetency'),
        ),
        migrations.RemoveField(
            model_name='group',
            name='badges',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='badges',
        ),
        migrations.AddField(
            model_name='group',
            name='badges',
            field=models.ForeignKey(blank=True, help_text='Badges displayed for this group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='experiences.badges'),
        ),
        migrations.AddField(
            model_name='participation',
            name='badges',
            field=models.ForeignKey(blank=True, help_text='Badge awarded for this specific participation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participations', to='experiences.badges'),
        ),
    ]
