# Generated by Django 4.2.23 on 2026-01-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0018_alter_badges_core_competencies_remove_group_badges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Whether the user has confirmed their email address'),
        ),
    ]
