# Generated by Django 4.2.23 on 2026-01-13 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideshowProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slideshow_slug', models.CharField(max_length=255)),
                ('current_h', models.IntegerField(default=0)),
                ('current_v', models.IntegerField(default=0)),
                ('max_percentage', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Slideshow Progress',
                'unique_together': {('user', 'slideshow_slug')},
            },
        ),
    ]
