"""
Django settings for our_site project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL = '/media/'
# Updated to use a proper media folder structure
MEDIA_ROOT = BASE_DIR / 'media'
# At the moment, the media root is the base directory which is not ideal
# MEDIA_ROOT = BASE_DIR 

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k0dq6k7#8)k$+h_ep+x2#oy_%=m8okvl3=x%dpgy17*j5#(y#u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# SECURITY WARNING: update this when you have the production host
ALLOWED_HOSTS = ['*']

# SECURITY WARNING: update this when you have the production host
CSRF_TRUSTED_ORIGINS = ["https://learn.whmiswise.com/"]


# Application definition

INSTALLED_APPS = [
    'django_startr',
    'experiences',
    'accounts',
    'polls',
    'translate',  # Add the new translate app
    'our_site.apps.OurSiteConfig',  # Add the main app with its management commands
    'our_site.apps.CustomAdminConfig', # Custom admin config to reorder apps
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'our_site.apps.ConstanceConfig',  # Use our custom app config instead of 'constance'
    'constance.backends.database',
    'debug_toolbar',  # Add Django Debug Toolbar
    'slideshows', # Add the new slideshows app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',  # Add Django Debug Toolbar middleware
    'experiences.middleware.ModelVisibilityMiddleware',
]

ROOT_URLCONF = 'our_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Add this line to include project-level templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'constance.context_processors.config',  # Add constance context processor
                'our_site.context_processors.random_quote',  # Inject random_quote when enabled
            ],
        },
    },
]

WSGI_APPLICATION = 'our_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Database has been moved to a dedicated DB folder
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db' / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/auth/login/'
LOGIN_REDIRECT_URL = '/'

# Constance settings
CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'

# Cache configuration
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.path.join(BASE_DIR, 'tmp'),
        'TIMEOUT': 60 * 60 * 24 * 7,  # 1 week cache timeout
        'OPTIONS': {
            'MAX_ENTRIES': 1000,  # Maximum number of entries in the cache
        }
    }
}

CONSTANCE_CONFIG = {
    'SITE_FAVICON': ('', 'Optional site favicon path', str),
    'ADMIN_SITE_ICON': ('', 'Optional admin site icon path \n(leave empty to use SITE_FAVICON)', str),
    'SITE_TITLE': ('Start Site', 'Title for the site', str),
    'SITE_SUBTITLE': ('', 'Subtitle for the site', str),
    'ADMIN_SITE_TITLE': ('Startr Administration', 'Title for the Startr Powered admin site', str),
    'QUOTES_ENABLED': (True, 'Enable quotes on the site', bool),
    'QUOTES_LIST': ('[]', 'List of quotes in JSON format. Example: [{"text":"Quote text","author":"Author name"}]', str),
    'SMART_SELECT_ENABLED': (True, 'Enable smart select on the site', bool),
    'SIGNUP_MESSAGE': ('Welcome to the Startr Powered site!', 'Message to display on the signup page', str),
    'SIGNUP_NEW_ACCOUNTS_PENDING': (True, 'Require new accounts to be approved by an admin', bool),
    'SIGNUP_NEW_ACCOUNTS_PENDING_MESSAGE': ('Your account has been created, but it needs to be approved by an admin before you can log in.', 'Message to display on the signup page when new accounts are pending approval', str),
    'SIGNUP_NOTIFICATION_EMAILS': ('[]', 'List of email addresses that should receive notifications about new user signups (JSON format). Example: ["admin@example.com", "support@example.com"]', str),
    'ADMIN_NOTIFICATION_EMAILS': ('[]', 'List of email addresses that should receive all staff/admin notifications (JSON format). Example: ["admin@example.com", "manager@example.com"]', str),
}

CONSTANCE_CONFIG_FIELDSETS = {
    '1. Site Settings': (
        'SITE_FAVICON',
        'SITE_TITLE',
        'SITE_SUBTITLE',
    ),
    '1.1 Signup Settings': {
        'fields': (
            'SIGNUP_MESSAGE',
            'SIGNUP_NEW_ACCOUNTS_PENDING',
            'SIGNUP_NEW_ACCOUNTS_PENDING_MESSAGE',
        ),
        'collapse': True
    },
    '2. Quotes': {
        'fields': (
            'QUOTES_ENABLED',
            'QUOTES_LIST',
        ),
        'collapse': True
    },
    '3. Admin Settings': {
        'fields': (
            'ADMIN_SITE_ICON',
            'ADMIN_SITE_TITLE',
            'SMART_SELECT_ENABLED',
            'SIGNUP_NOTIFICATION_EMAILS',
            'ADMIN_NOTIFICATION_EMAILS',
        ),'collapse': True
    },
}

# Configuration for Django Debug Toolbar
INTERNAL_IPS = [
    '127.0.0.1',
    'localhost',
]

# Docker configuration for Debug Toolbar
# This allows Debug Toolbar to work inside Docker containers
# by detecting the Docker host's IP
import socket
hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
INTERNAL_IPS += ['.'.join(ip.split('.')[:3] + ['1']) for ip in ips]

# Debug Toolbar configuration
#DEBUG_TOOLBAR_CONFIG = {
    #'SHOW_TOOLBAR_CALLBACK': lambda request: DEBUG,
#}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'info@whmiswise.com'  # Replace with your actual email
EMAIL_HOST_PASSWORD = 'afnlunnyyvfrkmea'  # Use a secure method!
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

VERSION = '0.0.1'

